project:
  type: website
  output-dir: docs

website:
  title: "Ashish Khatke"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Bio
        href: about.qmd
      - text: Posts
        href: posts.qmd
  page-footer:
    left: "Copyright 2022, Ashish Khatke"
    right:
      - icon: github
        href: https://github.com/khatkeashish

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



